name: "zerodte"

services:
  zerodte_httpd:
    image: httpd:latest
    container_name: zerodte_httpd
    ports:
      - "7080:80"
      - "8443:443"
    volumes:
      # base config
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:cached
      - ./apache/zerodte.conf:/usr/local/apache2/conf/extra/zerodte.conf:cached
      # Self-signed certificate
      - ./apache/ssl/localhost.key:/usr/local/apache2/conf/server.key:cached
      - ./apache/ssl/localhost.crt:/usr/local/apache2/conf/server.crt:cached

networks:
  default:
    name: zerodte-stack
    driver: bridge
